dist: trusty
language: node_js
node_js:
- '9'
deploy:
  provider: npm
  email: altay.aydemir@gmail.com
  api_key:
    secure: YO7GpdOKhICPcRVReWWcz53tVlRWq8/w0yDWbfjPSSNCUB82P+H1UVkiFXUezhS3OGa9OkGHnC4u698rrtSlVy97KmjVeRiDdc8nF41kZ0vjXNE5DsZzaflZaGgYXr6QF77uboB7Bsffv3YmRhea49VC2yXd/NDvW4fcNLMBpCZGhoIAaXMXl9/u9b30uFwtQ5iV28rpc/SylQVKfoBeHCIGOjshkpVQ0xFHdtewWl/rI6oThem+H/qKDrGp8iV7fVgQo32NoAhuyiSWSY+164pa6sAeTMRQHacrbAbZluozzuRXzBRc5fQaLM7vxM5q78OaGiUrlAj5jALMl0EppYkO3zjP/dNhQ7onnULTwelPi/0l7Hz0WoUj8H1uuM+uLJtLeXvuYH9F9OT6Wyj77LVt52smEJ5vRhU26dCZ/wEdRdJ1ajJXcBAg5VBF3XrFHpZ93Wi0NNZ+z390Nfcqk5BpIDZX6fhGS3OAL5h80CLk+bICRRK7w+NqUJ1ztJRbdfpCqpneI8oE6+cG9KdRBYP1CrFNRq6rNxXzaE+pHSnO1C+u1zpUF79Ra9TN/YLr6nO4gYuoWaLpxGuRX/C15PjzDYArleWvW5Tk9X4VS5/4ufKFgCTR18GVkz4VmdV9ysQoU/T1NHk5RBdtW2i2S9ez5iIRwM8UTjFgaVRuMMY=
  on:
    tags: true
    repo: accept-nano/accept-nano-client
